reset role;
select test_assert((select bool_and(web_calls_enabled and web_messages_enabled) from push_devices),'legacy web categories default enabled');
select test_assert(not has_function_privilege('anon','set_web_push_preferences(text,boolean,boolean)','execute'),'anonymous preferences denied');
set role authenticated;
set "request.jwt.claim.sub"='00000000-0000-0000-0000-000000000002';
select set_web_push_preferences('native-web-device-token',false,true);
reset role;
select test_assert((select not web_calls_enabled and web_messages_enabled from push_devices where token='native-web-device-token'),'owned web call preference persists independently');
set role authenticated;
select test_error($$select set_web_push_preferences('native-android-a-token',false,false)$$,'Owned web push device required');
select test_error($$select set_web_push_preferences('unknown-token',false,false)$$,'Owned web push device required');
select test_error($$select set_web_push_preferences('native-web-device-token',null,false)$$,'Push preferences required');
set "request.jwt.claim.sub"='00000000-0000-0000-0000-000000000003';
select test_error($$select set_web_push_preferences('native-web-device-token',true,true)$$,'Owned web push device required');
set "request.jwt.claim.sub"='00000000-0000-0000-0000-000000000001';
select test_error($$select set_web_push_preferences('native-web-device-token',true,true)$$,'Owned web push device required');
reset role;
update chat_calls set status='ended' where status in('ringing','accepted');
set role authenticated;
set "request.jwt.claim.sub"='00000000-0000-0000-0000-000000000001';
select (start_chat_call('00000000-0000-0000-0000-000000000010','audio')).id as pref_call \gset
reset role;
select test_assert(not private.native_call_delivery_allowed(d),'muted web invitation never reaches provider') from private.native_call_deliveries d join push_devices p on p.id=d.device_id where d.call_id=:'pref_call' and p.platform='web';
select test_assert(private.native_call_delivery_allowed(d),'native invitation unchanged by web preference') from private.native_call_deliveries d join push_devices p on p.id=d.device_id where d.call_id=:'pref_call' and p.token='native-android-a-token';
set role authenticated;
set "request.jwt.claim.sub"='00000000-0000-0000-0000-000000000002';
select set_web_push_preferences('native-web-device-token',true,false);
reset role;
select test_assert(private.native_call_delivery_allowed(d),'queued web invitation uses current unmuted category') from private.native_call_deliveries d join push_devices p on p.id=d.device_id where d.call_id=:'pref_call' and p.platform='web';
select test_assert((select web_calls_enabled and not web_messages_enabled from push_devices where token='native-web-device-token'),'messages preference independent from calls');
update profiles set status='suspended' where id='00000000-0000-0000-0000-000000000002';
set role authenticated;
select test_error($$select set_web_push_preferences('native-web-device-token',false,false)$$,'Active company profile required');
reset role;
update profiles set status='active' where id='00000000-0000-0000-0000-000000000002';
update push_devices set disabled_at=now() where token='native-web-device-token';
set role authenticated;
select test_error($$select set_web_push_preferences('native-web-device-token',false,false)$$,'Owned web push device required');
reset role;
update push_devices set disabled_at=null where token='native-web-device-token';
